CREATE TABLE
    CONF_INTEGRATION_ACESS_TOKEN
(
    TOKEN_ID           NUMBER DEFAULT SEQ_INTEGRATION_TOKEN_ID.NEXTVAL,
    TOKEN              VARCHAR2(800),
    USED_FLG           VARCHAR2(1),
    CRTD_DT            DATE,
    CRTD_BY            VARCHAR2(80)
);



CREATE OR REPLACE TRIGGER TRG_CONF_INTEGRATION_ACESS_TOKEN_INS
    BEFORE INSERT
    ON CONF_INTEGRATION_ACESS_TOKEN
    FOR EACH ROW
BEGIN
    :NEW.CRTD_DT := SYSDATE;
    :NEW.CRTD_BY := NVL(V('APP_USER'), USER);
END;
/

