CREATE TABLE L0_FAKTUROID_EXPENSES_INTEGRATION
(
    ID                         VARCHAR2(500),
    CUSTOM_ID                  VARCHAR2(500),
    NUM                        VARCHAR2(500),
    ORIGINAL_NUMBER            VARCHAR2(500),
    VARIABLE_SYMBOL            VARCHAR2(500),
    SUPPLIER_NAME              VARCHAR2(500),
    SUPPLIER_STREET            VARCHAR2(500),
    SUPPLIER_CITY              VARCHAR2(500),
    SUPPLIER_ZIP               VARCHAR2(500),
    SUPPLIER_COUNTRY           VARCHAR2(500),
    SUPPLIER_REGISTRATION_NO   VARCHAR2(500),
    SUPPLIER_VAT_NO            VARCHAR2(500),
    SUPPLIER_LOCAL_VAT_NO      VARCHAR2(500),
    SUBJECT_ID                 VARCHAR2(500),
    STATUS                     VARCHAR2(500),
    DOCUMENT_TYPE              VARCHAR2(500),
    ISSUED_ON                  VARCHAR2(500),
    TAXABLE_FULFILLMENT_DUE    VARCHAR2(500),
    RECEIVED_ON                VARCHAR2(500),
    DUE_ON                     VARCHAR2(500),
    REMIND_DUE_DATE            VARCHAR2(500),
    PAID_ON                    VARCHAR2(500),
    LOCKED_AT                  VARCHAR2(500),
    DESCRIPTION                VARCHAR2(500),
    PRIVATE_NOTE               VARCHAR2(500),
    TAGS                       VARCHAR2(500),
    BANK_ACCOUNT               VARCHAR2(500),
    IBAN                       VARCHAR2(500),
    SWIFT_BIC                  VARCHAR2(500),
    PAYMENT_METHOD             VARCHAR2(500),
    CUSTOM_PAYMENT_METHOD      VARCHAR2(500),
    CURRENCY                   VARCHAR2(500),
    EXCHANGE_RATE              VARCHAR2(500),
    TRANSFERRED_TAX_LIABILITY  VARCHAR2(500),
    VAT_PRICE_MODE             VARCHAR2(500),
    SUPPLY_CODE                VARCHAR2(500),
    PROPORTIONAL_VAT_DEDUCTION VARCHAR2(500),
    TAX_DEDUCTIBLE             VARCHAR2(500),
    SUBTOTAL                   VARCHAR2(500),
    TOTAL                      VARCHAR2(500),
    NATIVE_SUBTOTAL            VARCHAR2(500),
    NATIVE_TOTAL               VARCHAR2(500),
    HTML_URL                   VARCHAR2(500),
    URL                        VARCHAR2(500),
    SUBJECT_URL                VARCHAR2(500),
    CREATED_AT                 VARCHAR2(500),
    UPDATED_AT                 VARCHAR2(500)
);


grant all on L0_FAKTUROID_EXPENSES_INTEGRATION to INVOLVE_APEX